name: Check for package updates with nvcheck

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  nvchecker:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Setup environment
        run: |
          echo "RUNNER_TEMP=$RUNNER_TEMP" > "$GITHUB_ENV"
          pacman -Syu --noconfirm git nodejs just fd nvchecker
          mkdir -p ~/.config/nvchecker/
          cat <<'EOF' > ~/.config/nvchecker/keyfile.toml
          [keys]
          github = "${{ github.token }}"
          "codeberg.org" = "${{ secrets.CODEBERG_TOKEN }}"
          EOF
      - uses: actions/checkout@v6
      - name: Check for updates
        run: |
          just nvcheck > "$RUNNER_TEMP"/nvcheck.output
          just nvtake --all
      - uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ github.token }}
          branch: "updates"
          title: "Updates"
          commit-message: "Update versions.json"
          body-path: "${{ env.RUNNER_TEMP }}/nvcheck.output"
          add-paths: versions.json